### ISSUE TITLE
Debugging oceanv3 netlist

### ISSUE THREAD

**Issue by trangnv** [tokenspice/tokenspice#124]
File `tokenspice/agents/SpeculatorAgent.py`, line 58, `del pool_agents[pool_name]` is not working

**Comment by trangnv** [comment]
Another error is appending `rugged_pool` in `PublisherAgent`
```python
if self._doRug():
            if len(self.pools) > 0:
                state.rugged_pools.append(self.pools[-1]) 
```
`state.rugged_pools` will append every time Agent takes step

**Comment by trentmc** [comment]
Hi @trangnv , I just merged your PR. Is this issue complete now? If yes, please close it.
