### ISSUE TITLE
Use Local Memory Type Variable Instead of Global Storage Type Variable in Event to Save Gas

### ISSUE THREAD

**Issue by Ether1oop** [tokenspice/tokenspice#166]
Hi, we recently have conducted a systematic study about Solidity event usage, evolution, and impact, and we are attempting to build a tool to improve the practice of Solidity event use based on our findings. We have tried our prototype tool on some of the most popular GitHub Solidity repositories, and for your repository, we find a potential optimization of gas consumption arisen from event use.  

The point is that when we use emit operation to store the value of a certain variable, local memory type variable would be preferable to global storage type (state) variable if they hold the same value. The reason is that an extra SLOAD operation would be needed to access the variable if it is storage type, and the SLOAD operation costs 800 gas.

For your repository, we find that the following event use can be improved:

- [DataTokenTemplate.sol](https://github.com/tokenspice/tokenspice/blob/main/sol057/contracts/oceanv3/templates/DataTokenTemplate.sol)
**function name:**&emsp;*proposeMinter*
**event name:**&emsp;&emsp;*MinterProposed*
**variable:**&emsp;&emsp;&emsp;&emsp;*_proposedMinter->newMinter*
```Solidity
    function proposeMinter(address newMinter) 
        external 
        onlyMinter 
    {
        _proposedMinter = newMinter;
        emit MinterProposed(
            msg.sender,
            _proposedMinter
        );
    }
```

- [BPool.sol](https://github.com/tokenspice/tokenspice/blob/main/sol080/contracts/oceanv4/pools/balancer/BPool.sol)
**function name:**&emsp;*updatePublishMarketFee*
**event name:**&emsp;&emsp;*PublishMarketFeeChanged*
**variable:**&emsp;&emsp;&emsp;&emsp;*_publishMarketCollector->_newCollector*
```Solidity
    function updatePublishMarketFee(address _newCollector, uint256 _newSwapFee) external {
        require(_publishMarketCollector == msg.sender, "ONLY MARKET COLLECTOR");
        require(_newCollector != address(0), "Invalid _newCollector address");
        require(_newSwapFee ==0 || _newSwapFee >= MIN_FEE, "ERR_MIN_FEE");
        require(_newSwapFee <= MAX_FEE, "ERR_MAX_FEE");
        _publishMarketCollector = _newCollector;
        _swapPublishMarketFee = _newSwapFee;
        emit PublishMarketFeeChanged(msg.sender, _publishMarketCollector, _swapPublishMarketFee);
    }
```

- [MockOldDT.sol](https://github.com/tokenspice/tokenspice/blob/main/sol080/contracts/oceanv4/utils/mock/MockOldDT.sol)
**function name:**&emsp;*proposeMinter*
**event name:**&emsp;&emsp;*MinterProposed*
**variable:**&emsp;&emsp;&emsp;&emsp;*_proposedMinter->newMinter*
```Solidity
    function proposeMinter(address newMinter) 
        external 
        onlyMinter 
    {
        _proposedMinter = newMinter;
        emit MinterProposed(
            msg.sender,
            _proposedMinter
        );
    }
```

- [V3DataTokenTemplate.sol](https://github.com/tokenspice/tokenspice/blob/main/sol080/contracts/oceanv4/v3/V3DataTokenTemplate.sol)
**function name:**&emsp;*proposeMinter*
**event name:**&emsp;&emsp;*MinterProposed*
**variable:**&emsp;&emsp;&emsp;&emsp;*_proposedMinter->newMinter*
```Solidity
    function proposeMinter(address newMinter) 
        external 
        onlyMinter 
    {
        _proposedMinter = newMinter;
        emit MinterProposed(
            msg.sender,
            _proposedMinter
        );
    }
```
Do you find our results useful? Your reply and invaluable suggestions would be greatly appreciated, and are vital for improving our tool. Thanks a lot for your time!

**Comment by trentmc** [comment]
Spam. Closing.
