### ISSUE TITLE
TokenSpice for Off-chain + On-chain behavior modeling

### ISSUE THREAD

**Issue by 0xPravar** [tokenspice/tokenspice#168]
Hi, 

I was wondering if we can interface blockchain interaction using TokenSpice with agent based models built using other python frameworks like Mesa or Repast?

I am looking to model and simulate a system with both off-chain and on-chain interactions. And we plan to be multi chain as bulk of the functionality is off chain.  

Can TokenSpice be used to model such a case (both off-chain and on-chain together)?

**Comment by trentmc** [comment]
Hello, yes this can be done, easily. TokenSPICE agent can have whatever you want under the hood. Right now there are pure-py agents and EVM-based ones. But you could readily add others. REST APIs, multiple VMs, etc. Play with the code, you'll see, it's very simple which makes it easy to extend.
