### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by 0xPravar** [tokenspice/tokenspice#169]
While following the installation instructions, I am getting this error upon running `pip install -r requirements.txt`

```
...

INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of black to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 7), black==22.3.0, click==8.1.3, platformdirs==2.5.2, pytest==6.2.5 and tomli==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    eth-brownie 1.19.3 depends on pyyaml==5.4.1
    eth-brownie 1.19.2 depends on pyyaml==5.4.1
    The user requested black==22.3.0
    eth-brownie 1.19.1 depends on black==22.6.0
    eth-brownie 1.19.0 depends on pyyaml==5.4.1
    eth-brownie 1.18.2 depends on pyyaml==5.4.1
    The user requested platformdirs==2.5.2
    
...

```

I installed eth-brownie and other packages separately using pip install on command line. Can this cause issue with functioning of the TokenSpice engine?

tsp run and plot seem to be working with the example netlists provided.

**Comment by trentmc** [comment]
> I installed eth-brownie and other packages separately using pip install on command line. Can this cause issue with functioning of the TokenSpice engine?

There shouldn't be issues wrt TokenSPICE running.

But as you've described, it's causing problems in the installation. Brownie is especially finicky.

Did you try to install using the exact install instructions, including creating a virtualenv etc?

**Comment by 0xPravar** [comment]
Yes. I followed the instructions exactly as specified step by step. Except that I did not need to do nvm installation. I also tried it on an alternate machine, but the same issue came up while running requirements.txt. 

Another issue I noticed is that `ganache-cli` is now deprecated.

**Comment by trentmc** [comment]
Thanks for the info. I hope to dig into this next week.

If it's urgent for you: in requirements.txt, change or loosen the specific version requirements for the dependencies with issues. See what works.

**Comment by trentmc** [comment]
Hello, thanks for your patience. I did a bunch of changes yesterday that loosen up the requirements.py dependencies a lot.

Could you try now and see if it works?

(FYI not all unit tests are passing yet, but don't worry about that. WIP by me)

**Comment by 0xPravar** [comment]
Hi. Thank You for making the changes. Apologies for not responding earlier. Somehow I missed the notification for this comment. 

I tried to do a fresh install TokenSpice following the instructions. I still get errors while directly using the requirements.txt file.    Some error extracts after running `pip install -r requirements.txt`

```
Collecting pyyaml<6.0.0,>=5.3.0
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/pravar/Documents/Nunet/Testing/tokenspice/venv/bin/python3 /Users/pravar/Documents/Nunet/Testing/tokenspice/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/z3/j7c_j0551v1cdrsw9x2p35sw0000gn/T/tmp9brk6rky
       cwd: /private/var/folders/z3/j7c_j0551v1cdrsw9x2p35sw0000gn/T/pip-install-f4nqry_n/pyyaml_9ec87d8684644c1682639a1b230dc6eb
  Complete output (62 lines):
  /private/var/folders/z3/j7c_j0551v1cdrsw9x2p35sw0000gn/T/pip-build-env-4xyuv2g1/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!
  
          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.
  
          By 2023-Oct-30, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.
  
          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************
  
  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/Users/pravar/Documents/Nunet/Testing/tokenspice/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    .
    .
    .
    File "<string>", line 201, in get_source_files
    File "/private/var/folders/z3/j7c_j0551v1cdrsw9x2p35sw0000gn/T/pip-build-env-4xyuv2g1/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  ```
  ```
  .
  .
  .
  WARNING: Discarding https://files.pythonhosted.org/packages/7f/9f/105f485c2d68ba611b90ac00f717b1c8fbb5d2229ce9e17d9f6c21385aab/coverage-3.0.tar.gz#sha256=d89bfa53c519d154cffd8295f63eaa226142cfbba98bd1cb8a02bd0da4b536dc (from https://pypi.org/simple/coverage/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
INFO: pip is looking at multiple versions of typing-extensions to determine which version is compatible with other requirements. This could take a while.
Collecting typing-extensions
  Downloading typing_extensions-4.7.0-py3-none-any.whl (33 kB)
  Downloading typing_extensions-4.6.3-py3-none-any.whl (31 kB)
  Downloading typing_extensions-4.6.2-py3-none-any.whl (31 kB)
  .
  .
  .
  INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  .
  .
  .
  ```
  The installer gets stuck at this stage.

**Comment by idrees535** [comment]
File "/tmp/pip-build-env-qj8ys7x5/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-qj8ys7x5/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-qj8ys7x5/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-qj8ys7x5/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-qj8ys7x5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Getting similar kind of issue with installation of eth brownie, following the exact installation instructions, have tried different venv with python versions (3.8,3.9,3.10,3.11)

**Comment by trentmc** [comment]
Glad you could solve it!
