### ISSUE TITLE
Implement rest of DataConsumerAgent, unskip its tests

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#19]
**Is your feature request related to a problem? Please describe.**

From [Ocean v3 netlist](https://github.com/tokenspice/tokenspice/blob/main/assets/netlists/oceanv3/about.md), here is 
DataconsumerAgent's functionality. It has two key functions: buyDT() and consumeDT().

![dataconsumer](https://user-images.githubusercontent.com/5305452/129683345-d55988c7-c6a1-4ee2-b3a3-db5a02292f13.png)

The commit https://github.com/oceanprotocol/tokenspice2/commit/79c52ebabbca0add15d62bf9d081915c94f1ad13 fleshed out buyDT(), for the most part. But there's more to do, see below.

**Describe the solution you'd like**

- [x] buyDT(): implement proper tests, make changes until tests pass
- [ ] consumeDT(): implement consumeDT(), implement tests, make changes until tests pass

**Comment by trentmc** [comment]
Hi @nvtrang91. An update...

1. I checked your PR locally. Both tests failed, there were two bugs. I fixed them. I don't know why they didn't show up in the hacking session yesterday. Nonetheless, all good now. I just merged your PR.

2. I went back to confirm that everything is done for DataconsumerAgent. And I realized that there is more to go: buyDT() was one part, but we still need consumeDT(). The Ocean V3 netlist makes it clear. I updated the issue accordingly, including showing exactly what's DataconsumerAgent does.

For (2), @nvtrang91 would you like to take a swing at consumeDT() ? In the netlist image, you can see its inputs and outputs, just like there are inputs and outputs displayed for buyDT().

**Comment by nvtrang91** [comment]
Hi @trentmc,
Totally forgot about consumeDT too, I'll work on that for the next session.
Cheers.
