### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#25]
**Is your feature request related to a problem? Please describe.**
To help maintain quality of this repo, have continuous integration (CI).

In the CI run, it should do at least:
* all static type checking via `mypy ./`, getting no errors or warnings
* all unit tests via `pytest`

**Describe the solution you'd like**
Add Github actions for CI.

**Describe alternatives you've considered**
Using Travis or Github actions. 

I recommend the latter, to not add new dependencies and keep the flow simple. Ocean components started with Travis and migrated to Github actions, with success. 

**Additional context**
Look at github.com/oceanprotocol/ocean.py for example CI. And elsewhere.

https://lab.github.com/githubtraining/github-actions:-continuous-integration
https://lab.github.com/githubtraining/github-actions:-hello-world
https://github.com/trentmc/hello-github-actions/pull/2

**Comment by LinuxIsCool** [comment]
If you get this working then see #26 and #27 which would be natural extensions.

**Comment by trentmc** [comment]
Johann demo'd his WIP on this today.
