### ISSUE TITLE
Implement Ocean V3 market dynamics, run simulations, tune as needed

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#28]
- [x] Finish writing Python-level agent behaviors for new agents
- [x] Wire new agents into system-level design 
- [x] Replicate Ocean V3 market dynamics: run simulations and tune as needed

**Comment by trentmc** [comment]
Trang demo'd his WIP on this today.

**Comment by trangnv** [comment]
A branch that contains WIP code of ocean V3
https://github.com/tokenspice/tokenspice/tree/WIP-oceanV3_netlist
Some notes:
- There are 4 agents: publisher (create datatoken, pool every 7 days), consumer, staker, stakerSpeculator
- KPIs only track agents OCEAN
- Plot (from KPIs)
![Agents_OCEAN_LINEAR](https://user-images.githubusercontent.com/35219743/135892193-81fff153-69cf-4225-9b63-67c28f63489a.png)

Somethings to add to complete this issue: @trentmc @richardblythman 
- KPI to track DT, BPT, maybe price them in OCEAN?
- add other agents that inherits from current agents?

**Comment by trentmc** [comment]
@trangnv do you consider this issue done?

(I'm thinking yes)

If yes, do you see any specific follow-ups on oceanv3 netlist? Eg more Q's?

**Comment by trangnv** [comment]
I think this is done. Maybe just some renaming needed if you prefer @trentmc ?

**Comment by trentmc** [comment]
Thanks.

We can rename as part of our work on oceanv4, if we see the need. So let's close this:)
