### ISSUE TITLE
Be able to simulate arbitrary solidity code

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#52]
**Is your feature request related to a problem? Please describe.**
Right now the README makes it easy to get smart contracts running in ganache by leveraging github.com/oceanprotocol/contracts. This has a friendly fork of Balancer V2, and other Ocean code.

But there are many scenarios where we want other smart contracts, or even to vary those.

**Describe the solution you'd like**
Make it easy to simulate arbitrary solidity code, rather than bias to the Ocean contracts.

**Prerequisites:**
- first #63 - conda -> pip
- then #71 - .sol into assets/, use brownie

**Comment by LinuxIsCool** [comment]
#63 Might help here as it offers an alternative installation without conda, thus enabling brownie.

**Comment by trentmc** [comment]
> #63 Might help here as it offers an alternative installation without conda, thus enabling brownie.

I've updated #63. It's now "replace conda with pip". Not as an alternative installation, as _the_ installation. Therefore solving #63 will help a lot for this issue.

**Comment by trentmc** [comment]
Changed from high -> mid priority to help others understand what issues are even higher priority than this

**Comment by trentmc** [comment]
It's now easy to have arbitrary solidity code! :)

#71 took care of it. [This comment](https://github.com/tokenspice/tokenspice/issues/71#issuecomment-979804420) has more details.
