### ISSUE TITLE
Consider removing some web3engine/models/ py files in favour of importing oceanpy

### ISSUE THREAD

**Issue by LinuxIsCool** [tokenspice/tokenspice#53]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a simplification. DRY <-> The same code is repeated here and in [oceanpy models directory](https://github.com/oceanprotocol/ocean.py/tree/main/ocean_lib/models). That code could be maintained in oceanpy and imported here in tokenspice. This is loosely related to #52 in consideration of a standard way of integrating solidity code.

**Describe the solution you'd like**
Tokenspice imports ocean.py and other web3py infrastructure instead of housing it directly.

**Describe alternatives you've considered**
The alternative is to leave the web3engine code here in the repo and grow out a collection of web3 engine modules directly here in the repository instead of importing. 

**Additional context**
Trent discusses this topic in the TE Academy Ocean markets study group on July 22 2021.

**Comment by trentmc** [comment]
While this is a cool idea, it's gonna cause more problems than it's worth right now. Oceanpy code is evolving a fair bit, especially with the upcoming oceanv4. 

So, closing.
