### ISSUE TITLE
web3 conda package

### ISSUE THREAD

**Issue by step21** [tokenspice/tokenspice#58]
Hi, thanks for using my web3 conda package, you're the first I actually found in the wild using it. :) Though download stats suggest there are more.

**Comment by trentmc** [comment]
Cool!

Tbh we're having issues with conda, so we're moving to pure pip. Details in #63.

**Comment by step21** [comment]
Sure. Mixing things is always problematic. If you use pip now, I'd suggest using pipenv right away. That way you can try to push people to not mix and match too much (i.e. mix with system python or whatever) because that will cause problems on pip too.

**Comment by trentmc** [comment]
Thanks for the tip. I updated #63 with that suggestion.
