### ISSUE TITLE
Wsloop Low-fidelity / Hi-fidelity (Marketplace Agent / Dataecosystem Agent)

### ISSUE THREAD

**Issue by LinuxIsCool** [tokenspice/tokenspice#61]
This is a small renaming. Will help with other Ocean V3 & V4 simulations.

The 'marketplaces agent' / 'dataecosystem agent' upgrade is more clearly described as 'wsloop-lowfi' and 'wsloop-highfi' respectively. 

Rename the current 'wsloop' netlist to 'wsloop base'. Then, 'wsloop base' can import from 'marketplace agent' as 'wsloop-lowfi' or 'dataecosystem agent' as 'wsloop-highfigh' based on a simple switch in its netlist. 

Thus, we can directly compare the simulation results while having modular, maintainable code that is not repeated.

**Comment by trentmc** [comment]
This is so tiny compared to other github issues, barely worth being an issue. Work like this will emerge naturally with work on oceanv3 and oceanv4. Therefore, closing this issue.
