### ISSUE TITLE
[pytest] tests break in native python venvs

### ISSUE THREAD

**Issue by le-dawg** [tokenspice/tokenspice#62]
I want to post this here for completeness's sake. When not using Anaconda python, the pytest scripts are  not aware of (manually) installed pip packages as per the environment.yml.

Also, I seem to have an issue with type hints not being accepted as legal syntax although I have 3.8.10 selected for the tokenspice venv.

These issues do not seem to affect operation of the oceanprotocol tokenspice environment.

**Comment by trentmc** [comment]
#63 has been updated, solving it will likely solve this issue.

**Comment by freedumbs00** [comment]
Please close this issue.  It is no longer a problem.
