### ISSUE TITLE
Use brownie directly. Leads to simpler code. Allows us to move external ocean contracts to internal, deploy internally. 

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#71]
We want to be able to modify Solidity on the fly. This issue is a stepping stone.

Status quo: 
- use ocean contracts from an external repo. Use npm & truffle in the external repo to deploy the contracts to ganache. 
- `web3engine/` holds oceanv3 drivers as interface between (a) oceanv3 solidity / EVM deployment and (b) agents that use them. This layer takes maintenance effort. It will add friction if we want to rapidly iterate on Solidity code. There's an opportunity to remove this layer if we use Brownie, because it casts each smart contract as a class, and each deployment of a smart contract as an object. Therefore much simpler code.

What we want:
- [ ] Copy .sol files in external Ocean repo https://github.com/oceanprotocol/contracts/tree/main/contracts Ocean repo, to new tokenspice directory assets/contracts/ocean. (Or, consider git sub-modules?) This goes hand-in-hand with...
- [ ] In place of Ocean repo's npm & truffle to deploy the contracts, deploy locally. **With brownie**
- [ ] Deprecate web3engine, web3tools. Agents use brownie classes  & objects _directly_ or with a thin interface

**Comment by JohannSuarez** [comment]
BK is going to take a crack at this issue. I'm leaving some notes for him.

Solving this issue will require modifications to the PyTest workflow, as it still operates on the existing status quo ( Assumes the contracts repo is outside of the tokenspice repo ).

Also please give consideration to tokenspice.ini's ARTIFACTS_PATH, which also points to the outside of the tokenspice repo.

**Comment by trentmc** [comment]
The commit gives many details of the changes. Copying them here for convenience, and to raise awareness.

Brownie:
* aggressive use of brownie, to unlock its power. Root directory `./` is treated as a brownie project, and loaded as BROWNIE_PROJECT in `util/constants.py`
* README updated accordingly: compiling, how connecting to ganache works, the non-need to {deploy contracts up front, need for addresses up-front}. Docs could get streamlined more, but at least it's got the info now:)
* new `contracts/` directory
* copy ocean (v3) contracts from github.com/oceanprotocol/contracts into `contracts/oceanv3`. Only things changed so far are the openzeppelin imports, and one SPDX line added
* got oceanv3 working end-to-end. Super-thin utility module 'oceanv3util.py`. New test sub-directory adapted from `web3engine/test/test*.py`. engine, agents, tests updated accordingly. 
* Add `Simpletoken.sol` to have tokens without relying on oceanv3 datatokens. Use Simpletoken for OCEAN.
* remove intermediate directory `assets`, so that `netlists` and `agents` are at `./`. Simpler.
* remove `web3engine`, `web3tools`, because brownie renders them obsolete
* refactoring some `util/` files for simplicity. globaltokens, constants, etc.
* can specify logging interval -- how often to log to stdout and csv.
* add `brownie-config.yaml`, so that I can specify compiler version (needed to get oceanv3 to compile)
