### ISSUE TITLE
Want live ganache logging *and* CI

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#81]
Issue #25 introduced CI, yay:)

As part of its solution, it put ganache.py's call to ganache-cli into the background via the `&` call. It enabled the same remote terminal to do more stuff.

Alas, this raises a small but likely easy to solve problem: when using ganache locally, you don't see any live logging. It feels quiet. And will harm the ability to manually debug.

Aim of _this_ issue: 
- Have live logging locally, eg by _not_ using the `&`
- Have CI 

Candidate approaches:
1. ganache.py gets an optional argument: `--run-in-background`. By default, it's false. But for the CI job it's true. 
2. ganache.py grabs an environmental variable whether to run in background. If no var, then it's false. 
3. in the CI job, _don't_ use ganache, simply use the whole expanded argument. Con: hurts maintainability

(1) is probably cleanest.

**Comment by trentmc** [comment]
@JohannSuarez this could be a nice one for you:)

**Comment by JohannSuarez** [comment]
@trentmc I'll get right on it! :D

**Comment by JohannSuarez** [comment]
Pull request approved, code merged this morning. Issue can be safely closed now :D
