### ISSUE TITLE
Auto-populate a newly created issue in kanban board

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#82]
I was trying to make github auto-populate a newly created issue in kanban board. But so far it hasn't worked.

I discovered that there are two steps:
1. Auto put a new issue into the project (MainProject)
2. Get board to auto populate with issues in that project. The board == the project, and the automation for this _is_ there I think (it's the weird card called "Automation Rules" in the left column)

**Comment by rsundar** [comment]
- Reinstalled project bot,
- Created a new board *[COPY] Main Project* where the automations work.

**Comment by trentmc** [comment]
Complete! Great job Rohan!
